{% set name = "logomaker" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/logomaker-{{ version }}.tar.gz
  sha256: d8c7501a7d6d7961cd68e5a44e939000ebf1b0c4197a0c9198351e1d681d3f6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - matplotlib-base
    - pandas

test:
  imports:
    - logomaker
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://logomaker.readthedocs.io
  summary: Package for making Sequence Logos
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmacdope
    - mikemhenry
